# Generated by Django 2.0.6 on 2018-07-18 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_case.TestCase')),
            ],
            options={
                'verbose_name': 'Связь тест плана и тест кейса',
                'verbose_name_plural': 'Связи тест планов и тест кейсов',
            },
        ),
        migrations.CreateModel(
            name='PlanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('success', 'Пройдён'), ('failed', 'Не пройден')], default='failed', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лог тест-плана',
                'verbose_name_plural': 'Логи тест-плана',
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('success', 'Пройдён'), ('in_process', 'В процессе'), ('failed', 'Не пройден')], default='failed', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('test_cases', models.ManyToManyField(through='test_plan.PlanCase', to='test_case.TestCase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест план',
                'verbose_name_plural': 'Тест планы',
            },
        ),
        migrations.AddField(
            model_name='planlog',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_plan.TestPlan'),
        ),
        migrations.AddField(
            model_name='planlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancase',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_plan.TestPlan'),
        ),
        migrations.AddField(
            model_name='plancase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
